### ISSUE TITLE
AUR install error

### ISSUE THREAD

**Issue by repsac-by** [rilian-la-te/vala-panel#13]
build ok
package ok
install error

>ошибка: не удалось завершить запрос (конфликтующие файлы)
>vala-panel-git: /usr/lib64 уже существует в файловой системе
>Обнаружены ошибки, пакеты не были обновлены.

**Comment by rilian-la-te** [comment]
Сейчас проверю.

2015-04-23 23:34 GMT+06:00 repsac <notifications@github.com>:

**Comment by rilian-la-te** [comment]
Please upgrade it with --force key. Some times ago it was be change into build system to support multilib, and Arch use link from /usr/lib64 to /usr/lib. And check after first force update. If reinstalling is ok - it is this.

**Comment by repsac-by** [comment]
Извини, что не на инглише.
 Мне кажется это не совсем нормально. Оно пытается переписать системную. директорию. Не снесет ли оно символическую ссылку /usr/lib64 к чертям?

**Comment by rilian-la-te** [comment]
Оно системную директорию перезаписать не пытается. Оно просто пытается
поставить /usr/lib64/libvalapanel.so, но находит там другой, неизвестный
pacman /usr/lib64/libvalapanel.so, который на самом деле
/usr/lib/libvalapanel.so. Если силой поставить - оно нормально его
перезапишет.

2015-04-23 23:46 GMT+06:00 repsac <notifications@github.com>:

**Comment by repsac-by** [comment]
Не, у меня сейчас нет такого файла, установка по чистой, специально.
>$ ls /usr/lib64/libvalapanel.so
ls: невозможно получить доступ к /usr/lib64/libvalapanel.so: Нет такого файла или каталога

>$ ls /usr/lib/libvalapanel.so
ls: невозможно получить доступ к /usr/lib/libvalapanel.so: Нет такого файла или каталога

**Comment by rilian-la-te** [comment]
Ща проверю. Система 64 бита?

2015-04-23 23:51 GMT+06:00 repsac <notifications@github.com>:

**Comment by repsac-by** [comment]
да, 64

**Comment by rilian-la-te** [comment]
Обновил пакет, пофиксил

**Comment by repsac-by** [comment]
thank you
