### ISSUE TITLE
Broken icons in launchbar

### ISSUE THREAD

**Issue by repsac-by** [rilian-la-te/vala-panel#15]
This happened after update 
 0.2.3.r19.g392210a-1 -> 0.2.8.1.r7.g98557c6-1

![vala-panel](https://cloud.githubusercontent.com/assets/4984191/7406870/fdf91da8-ef12-11e4-8402-cc8008d23e34.png)

**Comment by rilian-la-te** [comment]
Cat config, please.

**Comment by repsac-by** [comment]
````plugin-type='launchbar'
has-schema=true
can-expand=true
launch-buttons=['file:///home/repsac/Desktop/launcher/10-radio.desktop', 'file:///home/repsac/Desktop/launcher/40-Win7.desktop', 'file:///home/repsac/Desktop/launcher/50-WinXP.desktop', 'file:///home/repsac/Desktop/launcher/30-Debian01.desktop', 'geary.desktop', 'file:///home/repsac/Desktop/launcher/60-cam2.desktop', 'file:///home/repsac/Desktop/launcher/60-cam1.desktop']
position=1

**Comment by rilian-la-te** [comment]
cat some of desktop files, please. One of it is enough.

**Comment by repsac-by** [comment]
only geary.desktop displayed icon and only geary.desktop without absolute path

/home/repsac/Desktop/launcher/30-Debian01.desktop
```
[Desktop Entry]
Comment[ru_RU]=Starts the VirtualBox machine Debian01
Comment=Starts the VirtualBox machine Debian01
Encoding=UTF-8
Exec=/usr/lib/virtualbox/VirtualBox --comment "Debian01" --startvm "490f4d91-3623-4118-bca9-76ada153e2a2"
GenericName[ru_RU]=
GenericName=
Icon=/home/repsac/.local/share/icons/other/debian-1.png
MimeType=
Name=Debian01
Path=
StartupNotify=true
Terminal=false
TerminalOptions=
Type=Application
Version=1.0
X-DBUS-ServiceName=
X-DBUS-StartupType=
X-KDE-SubstituteUID=false
X-KDE-Username=

**Comment by repsac-by** [comment]
/home/repsac/Desktop/launcher/10-radio.desktop
```
[Desktop Entry]
Comment[ru_RU]=
Comment=
Exec=mpv --no-terminal --force-window --playlist /mnt/work/var/playlist/radio.m3u
GenericName[ru_RU]=
GenericName=
Icon=audio-headphones
MimeType=
Name=radio
NoDisplay=false
Path=
StartupNotify=true
Terminal=false
TerminalOptions=
Type=Application
X-DBUS-ServiceName=
X-DBUS-StartupType=none
X-KDE-SubstituteUID=false
X-KDE-Username=

**Comment by rilian-la-te** [comment]
It is fixed now?

**Comment by repsac-by** [comment]
yes, but geary.desktop moved to the end

**Comment by rilian-la-te** [comment]
In config also, or only in actual panel?

**Comment by repsac-by** [comment]
only in panel

**Comment by rilian-la-te** [comment]
will check it today.

**Comment by rilian-la-te** [comment]
Some question about incorrect order of geary:
1. How reordering it works?
2. What happened, if geary will be reordered on non-running panel? And on running?

**Comment by repsac-by** [comment]
Извини напишу так, а то начинаю терять суть.
вот так в конфиге
```
launch-buttons=['file:///home/repsac/Desktop/launcher/10-radio.desktop', 'geary.desktop', 'file:///home/repsac/Desktop/launcher/40-Win7.desktop', 'file:///home/repsac/Desktop/launcher/50-WinXP.desktop', 'file:///home/repsac/Desktop/launcher/30-Debian01.desktop', 'file:///home/repsac/Desktop/launcher/60-cam2.desktop', 'file:///home/repsac/Desktop/launcher/60-cam1.desktop']
```

То есть geary должен быть вторым.. а отображается последним.
 По работе вопросов нет, всё работает правильно.

**Comment by rilian-la-te** [comment]
А если переместить geary?
Что будет?

Попробуй при запущенной панели и при незапущенной.
И попробуй с перемещенный geary запустить панель и скажи, на каком он месте будет.

**Comment by repsac-by** [comment]
geary не перемещается.
Зато попробовал камеру переместить и получил интересный эффект :)

![vala-panel3](https://cloud.githubusercontent.com/assets/4984191/7411435/9f4d2a46-ef40-11e4-8ddc-ec24ca0867da.png)

**Comment by rilian-la-te** [comment]
Конфиг после перемещения запости.
Сейчас будем разбираться. раз уж взялся за launchbar.

**Comment by repsac-by** [comment]
Судя по всему конфиг остался без изменений.
В конфиге оказалось тепреь 2 ланчбара

>
[toplevel-settings]
strut=true
monitor=-1
background-type='image'
edge='right'
height=30
icon-size=24
auto-hide=false
enable-font-color=true
font-color='rgb(255,255,255)'
background-file='/usr/share/simple-panel/images/background.png'


autohide=false
use-background-color=true
background-color='rgb(136,138,133)'

alignment='end'
panel-margin=45

width=100

[2]
plugin-type='launchbar'
has-schema=true
can-expand=true
launch-buttons=['file:///home/repsac/Desktop/launcher/10-radio.desktop', 'geary.desktop', 'file:///home/repsac/Desktop/launcher/40-Win7.desktop', 'file:///home/repsac/Desktop/launcher/50-WinXP.desktop', 'file:///home/repsac/Desktop/launcher/30-Debian01.desktop', 'file:///home/repsac/Desktop/launcher/60-cam2.desktop', 'file:///home/repsac/Desktop/launcher/60-cam1.desktop']
position=1

[3]
plugin-type='separator'
has-schema=true
can-expand=true
size=4
show-separator=false
position=2                                                                                                                                                                                                                         
                                                                                                                                                                                                                                   
is-expanded=true                                                                                                                                                                                                                   
                                                                                                                                                                                                                                   
[12]                                                                                                                                                                                                                               
plugin-type='xembed'                                                                                                                                                                                                               
has-schema=false                                                                                                                                                                                                                   
is-expanded=false                                                                                                                                                                                                                  
position=5                                                                                                                                                                                                                         
                                                                                                                                                                                                                                   
[0]                                                                                                                                                                                                                                
plugin-type='menumodel'                                                                                                                                                                                                            
has-schema=true
position=0
model-file='/home/repsac/.config/vala-panel/vm.xml'
is-internal-menu=false
is-system-menu=false
is-menu-bar=false
repsac@surefire ~ $ cat .config/vala-panel/default/panels/panel 
[toplevel-settings]
strut=true
monitor=-1
background-type='image'
edge='right'
height=30
icon-size=24
auto-hide=false
enable-font-color=true
font-color='rgb(255,255,255)'
background-file='/usr/share/simple-panel/images/background.png'


autohide=false
use-background-color=true
background-color='rgb(136,138,133)'

alignment='end'
panel-margin=45

width=100

[2]
plugin-type='launchbar'
has-schema=true
can-expand=true
launch-buttons=['file:///home/repsac/Desktop/launcher/10-radio.desktop', 'geary.desktop', 'file:///home/repsac/Desktop/launcher/40-Win7.desktop', 'file:///home/repsac/Desktop/launcher/50-WinXP.desktop', '60-cam1.desktop', 'file:///home/repsac/Desktop/launcher/30-Debian01.desktop', 'file:///home/repsac/Desktop/launcher/60-cam2.desktop', 'file:///home/repsac/Desktop/launcher/60-cam1.desktop']
position=1

[3]
plugin-type='separator'
has-schema=true
can-expand=true
size=4
show-separator=false
position=2

is-expanded=true

[12]
plugin-type='xembed'
has-schema=false
is-expanded=false
position=5

[0]
plugin-type='menumodel'
has-schema=true
position=0
model-file='/home/repsac/.config/vala-panel/vm.xml'
is-internal-menu=false
is-system-menu=false
is-menu-bar=false

**Comment by rilian-la-te** [comment]
Где 2, не вижу. Выдели в предыдущем комменте каждый конфиг тегом.

**Comment by repsac-by** [comment]
Выделил.. Вообще всего по 2 стало   menumodel тоже

**Comment by rilian-la-te** [comment]
Я вижу тут такой конфиг:
```
[toplevel-settings]
strut=true
monitor=-1
background-type='image'
edge='right'
height=30
icon-size=24
auto-hide=false
enable-font-color=true
font-color='rgb(255,255,255)'
background-file='/usr/share/simple-panel/images/background.png'

autohide=false
use-background-color=true
background-color='rgb(136,138,133)'

alignment='end'
panel-margin=45

width=100

[2]
plugin-type='launchbar'
has-schema=true
can-expand=true
launch-buttons=['file:///home/repsac/Desktop/launcher/10-radio.desktop', 'geary.desktop', 'file:///home/repsac/Desktop/launcher/40-Win7.desktop', 'file:///home/repsac/Desktop/launcher/50-WinXP.desktop', '60-cam1.desktop', 'file:///home/repsac/Desktop/launcher/30-Debian01.desktop', 'file:///home/repsac/Desktop/launcher/60-cam2.desktop', 'file:///home/repsac/Desktop/launcher/60-cam1.desktop']
position=1

[3]
plugin-type='separator'
has-schema=true
can-expand=true
size=4
show-separator=false
position=2

is-expanded=true

[12]
plugin-type='xembed'
has-schema=false
is-expanded=false
position=5

[0]
plugin-type='menumodel'
has-schema=true
position=0
model-file='/home/repsac/.config/vala-panel/vm.xml'
is-internal-menu=false
is-system-menu=false
is-menu-bar=false
```
Он совершенно нормален.

**Comment by repsac-by** [comment]
точно.. я 2 раза cat сделал.. сорри :)

**Comment by repsac-by** [comment]
Перезапустил панель.. теперь восстановилось порядок поменялся, но пока делал скриншот.. Даже не трогал панель.. может мышкой только водил.. опять камера начала размножаться.
![vala-panel4](https://cloud.githubusercontent.com/assets/4984191/7411746/69f378de-ef43-11e4-9ef7-e24bfd22a22f.png)
![vala-panel5](https://cloud.githubusercontent.com/assets/4984191/7411749/6d6e84ea-ef43-11e4-931b-c922960039e5.png)

**Comment by repsac-by** [comment]
в том конфиге что я скинул у ланчбара появился лишний элемент без абсолютного пути '60-cam1.desktop'

**Comment by rilian-la-te** [comment]
Понятно. Я посмотрю, там id наверное, где-то неверно берется или присваивается. Не так, как раньше.

**Comment by repsac-by** [comment]
Вообще итог.. При перемещении элемент у которого абсолютный путь. Возникает новый элемент без базовым именем файла, при этом прежний элемент остается.

**Comment by rilian-la-te** [comment]
А если абсолютного пути нет, элемент переместить можно?

**Comment by repsac-by** [comment]
Ну вот у меня geary висит в конце.. я его хватаю двигаю и ничего.. Только если за предел панели тогда исчезает.

**Comment by rilian-la-te** [comment]
Теперь пробуй.

**Comment by repsac-by** [comment]
двигаеться.. но надо быть снайпером )))

**Comment by rilian-la-te** [comment]
В смысле?

**Comment by repsac-by** [comment]
Понял принцип, надо целить в ту иконку на место которой должно встать.. а я целил между иконок.

**Comment by rilian-la-te** [comment]
Попробуй новый релиз. Я тут вроде запилил ту фичу, которую ты хотел - добавление всей папки на launchbar. Ну и конфиг сделал до кучи. Так что снайпером теперь быть не надо:)

**Comment by repsac-by** [comment]
сейчас

**Comment by repsac-by** [comment]
с конфигом стало очень классно.. но не могу понять как добавить папку

**Comment by rilian-la-te** [comment]
На плюс ткни, а потом выбери вкладку файлы и поставь галочку и два раза щелкни на нужную папку. Что происходит. Если не работает - сие есть баг, сейчас пофиксим.

**Comment by repsac-by** [comment]
Галочку ставлю.. но оно не выбирает папку, а входит в неё

**Comment by rilian-la-te** [comment]
Сейчас поправлю, погоди.

**Comment by repsac-by** [comment]
Еще надпись горит "Приложения не найдены".
![vala-panel6](https://cloud.githubusercontent.com/assets/4984191/7420437/28b3d7f0-ef85-11e4-9b4c-3289ec9146e5.png)

**Comment by rilian-la-te** [comment]
Про надпись знаю. Как пофиксить - хз пока.

**Comment by repsac-by** [comment]
У меня новая нелепая просьба )))
Когда ланчер стал дружелюбным со своим конфигом, я начал его набивать и понял.. что приложения надо делить разделителем на группы. И тут мне пришлось лепить много ланчеров и разделителей. В итоге в апплетах сложно разобраться )))
Как решение можно добавить в ланчбар свой внутренний разделитель.

Еще вьюшка апплетов не растягивается вместе с окном настроек.
![vala-panel7](https://cloud.githubusercontent.com/assets/4984191/7420854/a4bb8034-ef88-11e4-9dec-7165517c317e.png)

**Comment by rilian-la-te** [comment]
Пофиксил баги (пришлось немного переделать галку, она теперь не в выбранной папке пытается брать файлы, а показываемые добавляет).

Встроенный разделитель в Launchbar - зачем? Такой можно запилить же.

**Comment by repsac-by** [comment]
Я имел ввиду, что бы разделитель можно было вставлять в рамках одного лачнбара.

**Comment by rilian-la-te** [comment]
Если так нужно, сделай себе кучу пустых desktop файлов, и придай им иконку разделителя. Ну или bootstrapов напихать попробуй.
Я не думаю, что превращать launchbar в комбайн сейчас - сильно годно. Разве что после 1.0.0 (ну и после армии).
До армии я хочу успеть сделать для панели 0.4 (смотри в баги и readme), немного подправить и пофиксить appmenu и sntray, и доделать extras (смотри баги).
Кстати, как тебе extras?

**Comment by repsac-by** [comment]
Получилось, при клике на файл добавились всё сразу.

**Comment by rilian-la-te** [comment]
Агась:) Там просто в GTK небольшой баг, неправильно немного работала.

**Comment by repsac-by** [comment]
Да с пыстыми desktop файлами я уже думал скорее всего попробую так сделать

**Comment by repsac-by** [comment]
Только вот что если сделать не это не галкой.. а кнопкой..    Добавить все файлы..
Зашел в директорию.. и нажал кнопку.

**Comment by rilian-la-te** [comment]
Проблем-то никаких:) Только некрасиво, боюсь, будет.

**Comment by rilian-la-te** [comment]
Держи с кнопкой

**Comment by repsac-by** [comment]
сейчас

**Comment by repsac-by** [comment]
супер!
Спасибо!
