### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Newt-OS** [rilian-la-te/vala-panel#22]
I would love to utilize this project in a project of my own (customized openSUSE image) and while it is available in the SUSE repos, I am having difficulty configuring it.  Would someone be able to point me to some documentation?  I'm attempting to replace LXpanel with Vala Panel.  Thanks!
~Newt

**Comment by rilian-la-te** [comment]
I does not have any documentation for it, but it is configured much like
LXPanel (because it is GTK3 LXPanel rewrite from scratch). Config files is
actually a GSettings databases, and panel itself can be expected via GTK
inspector. If you want explanations, write questions here:-)

**Comment by Newt-OS** [comment]
Ok.  I figured out most of the issues.
