### ISSUE TITLE
Old vapi files being used

### ISSUE THREAD

**Issue by mbellgb** [rilian-la-te/vala-panel#24]
The ones currently being used will throw an error during make, saying the glib.duplicateFunc doesn't exist. Perhaps it would be better to use a submodule instead?

**Comment by rilian-la-te** [comment]
With recent VAPIs all works?

**Comment by ObadiahCrowe** [comment]
My version of vapi is latest and I get this..

**Comment by rilian-la-te** [comment]
If you remove old VAPIs, project compiles?

**Comment by ObadiahCrowe** [comment]
From the package? or the system?

**Comment by rilian-la-te** [comment]
It is removed.
