### ISSUE TITLE
Icon Tasklist

### ISSUE THREAD

**Issue by Newt-OS** [rilian-la-te/vala-panel#25]
This is more of a feature request than an issue, but I was wondering if there were any plans to make an icons-only tasklist for Vala Panel?  I think it would be a valuable addition to the project, and I would be willing to work on writing it as a summer project.  I only wanted to check first because the Readme for Vala-Panel-Extras thanks Ikey Doherty for an icontasklist, and I don't want to reinvent what already exists.

~Newt

**Comment by rilian-la-te** [comment]
You can write it:-) of course:-) now I am in an army, so I cannot write
project (3 months remaining)

**Comment by rilian-la-te** [comment]
Added experimental Icontasklist (into WNCK).
