### ISSUE TITLE
Gtk-ERROR: GtkBox child Pager minimum width

### ISSUE THREAD

**Issue by JuHwon** [rilian-la-te/vala-panel#29]
When i installed the vala-panel-0.3.5-1_amd64-plugins-wnck.deb package.
The vala-panel does not start anymore (im starting it with `vala-panel -p default`) and i get the following output:

```
juhwon  ~/Downloads/vala-panel   master >> vala-panel -p default

** (vala-panel:9822): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-kIZV7QbRfE: Connection refused

(vala-panel:9822): GLib-GIO-CRITICAL **: g_menu_remove: assertion '0 <= position && position < menu->items->len' failed

(vala-panel:9822): Gtk-ERROR **: GtkBox child Pager minimum width: -1 < 0 for height 26
[1]    9822 trace trap (core dumped)  vala-panel -p default

```

**Comment by Newt-OS** [comment]
I was just going to file this same issue.  When starting Vala Panel via terminal (elsewhere it also does not start) I get the same error.
![what is this](https://cloud.githubusercontent.com/assets/16482777/15660838/13779a70-26a7-11e6-9be1-02994e1a5e72.png)

I found that starting the panel with a different profile caused it to launch correctly, which makes me think that it may be a problem with the profile's configuration file.  I really can't think of what would be making it crash though, and I don't understand what the error means.

**Comment by rilian-la-te** [comment]
It is Pager plugin bug. Just disable it for now.

**Comment by wesleyotugo** [comment]
`cp /etc/xdg/vala-panel ~/.config/`

**Comment by rilian-la-te** [comment]
With Pager it sometimes won't work, unfortunately. Now I in a way to rewrite a entire plugin system for 0.4 to fix this issue.

**Comment by rilian-la-te** [comment]
AFAIK fixed.
