### ISSUE TITLE
AppMenu not working for some GTK apps.

### ISSUE THREAD

**Issue by ASAPHAANING** [rilian-la-te/vala-panel#30]
I can get the AppMenu working with some applications like Mozilla products and some old SWT Java. My Firefox is 46.01 GTK+3. I get the following error regardless, on every launch:

`(vala-panel:2507): GLib-GIO-CRITICAL **: g_menu_remove: assertion '0 <= position && position < menu->items->len' failed`

Used CMAKE on Ubuntu 16.04 from the latest branch on github for all builds. I do get makefiles and I do get installations (No errors, and only two warnings building Vala-Panel (Some functions never used).

On top of that, most of the times when I right click the panel and request panel items or settings, the panel crashes with the following error log:
`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(vala-panel:2507): Gtk-WARNING **: gtk_window_set_titlebar() called on a realized window
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

** (vala-panel:2507): WARNING **: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545

** (vala-panel:2507): WARNING **: Failed to fetch type: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545

** (vala-panel:2507): WARNING **: Failed to fetch monitor: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545

** (vala-panel:2507): WARNING **: Failed to fetch maximized state: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545

** (vala-panel:2507): WARNING **: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545

** (vala-panel:2507): WARNING **: Failed to fetch type: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545

** (vala-panel:2507): WARNING **: Unable to fetch children: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.view' on object at path /org/ayatana/bamf/application/0x220c1a0

** (vala-panel:2507): WARNING **: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.application' on object at path /org/ayatana/bamf/application/0x220c1a0

** (vala-panel:2507): WARNING **: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545

** (vala-panel:2507): WARNING **: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545

** (vala-panel:2507): WARNING **: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545

** (vala-panel:2507): WARNING **: Failed to fetch property `_GTK_UNIQUE_BUS_NAME': GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545

** (vala-panel:2507): WARNING **: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/33554545
Segmentation fault
`

**Comment by rilian-la-te** [comment]
Will look for it after returning from army. In Debian Jessie all OK.

**Comment by rilian-la-te** [comment]
Do you have bamfdaemon running before AppMenu starts?

**Comment by St1rling** [comment]
How do you get it running in Arch?

**Comment by rilian-la-te** [comment]
Just install unity-gtk-module-standalone from AUR and add it to GTK_MODULES for gtk. For QT4 - appmenu-qt, for qt5 -appmenu-qt5, but it does not working. Does not know who, will look for it in Sat-Sun, if Pillars of Ethernity will not eat my time:)

**Comment by rilian-la-te** [comment]
Go to vala-panel-appmenu bugtracker:)
