### ISSUE TITLE
When adding vala-panel-appmenu it crashes

### ISSUE THREAD

**Issue by St1rling** [rilian-la-te/vala-panel#31]
This is all I get when I add the appmenu widget:

** (vala-panel:3024): ERROR **: Unable to get org.ayatana.bamf matcher: Error calling StartServiceByName for org.ayatana.bamf: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.ayatana.bamf exited with status 1
[1]    3024 trace trap (core dumped)  vala-panel

**Comment by rilian-la-te** [comment]
do you have bamfdaemon?

**Comment by St1rling** [comment]
Do now :) thanks

**Comment by rilian-la-te** [comment]
Closing it.
