### ISSUE TITLE
Overall problems on Manjaro/Arch

### ISSUE THREAD

**Issue by ibisoda** [rilian-la-te/vala-panel#32]
Hey there,

So I tried installing vala-panel on Manjaro and firstly I got this error message during build().

> CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:363 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:528 (_pkg_check_modules_internal)
  CMakeLists.txt:95 (pkg_check_modules)

I heard, you need to install gobject-introspection to make it work. So I did and I got through the installation process at least but now when I try to run vala-panel I get:

> ** (vala-panel:6119): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-kswKi4sTa0: Verbindungsaufbau abgelehnt

> ** (vala-panel:6119): WARNING **: application.vala:198: Config files are not found

So yeah, this is my problem. 
Also, when I try to install the app menu for vala-panel, it crashes during prepare().

>gobject-2.0.vapi:157.37-157.57: error: The type name 'GLib.DuplicateFunc' could not be found
		public T dup_data<T> (string key, GLib.DuplicateFunc<T> dup_func);
		                                  ^^^^^^^^^^^^^^^^^^^^^
gobject-2.0.vapi:160.44-160.64: error: The type name 'GLib.DuplicateFunc' could not be found
		public T dup_qdata<T> (GLib.Quark quark, GLib.DuplicateFunc<T> dup_func);
		                                         ^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 48 warning(s)
make[2]: *** [lib/CMakeFiles/vala-dbusmenu.dir/build.make:61: lib/vala-dbusmenu_valac.stamp] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:126: lib/CMakeFiles/vala-dbusmenu.dir/all] Fehler 2

**Comment by rilian-la-te** [comment]
Second means that you need to create some config files in ini format (or copy templates ) First and third will be fixed this evening.

**Comment by ibisoda** [comment]
Thanks for the quick reply, first of all.
I just used the config file you had provided and the panel showed up.

However, I'm still having problems. When I add the application menu to the panel, everything works fine. However, if I add e.g. a spacer or a clock, vala-panel just crashes.

> (vala-panel:1779): GLib-GIO-ERROR **: Settings schema 'org.valapanel.toplevel.menumodel' does not contain a key named 'clock-format'

Sorry, if I'm being a pain, I'm relatively new to the world of Linux.

**Comment by rilian-la-te** [comment]
1 & 3 fixed. What config file are you used?  I provided three:) And pacman -Ql vala-panel-git, please:)

**Comment by ibisoda** [comment]
I used the default one I think, but I guess I messed it up because I didn't copy it correctly. My bad.
Now I use the 'appmenu' template and it's all quite well... except for one thing. If I right click, nothing happens, no settings show up. And if I try to add something to the panel, nothing happens.

Anyway I just attached the output for pacman -Ql
[vala panel Ql.txt](https://github.com/rilian-la-te/vala-panel/files/374580/vala.panel.Ql.txt)

Also, are you sure, you fixed 3? I still can't install the appmenu properly...

**Comment by rilian-la-te** [comment]
try now, incorrect PKGBUILD was uploaded.

**Comment by ibisoda** [comment]
Yes, it works now. Thank you very much.

**Comment by rilian-la-te** [comment]
Closing it as fixed.
