### ISSUE TITLE
Add a GUI to configure without the need of a config file

### ISSUE THREAD

**Issue by Ufeldraku** [rilian-la-te/vala-panel#33]
Just as it says.

**Comment by rilian-la-te** [comment]
But we have a GUI:-) Just have a profile Locked and right-click to panel :-)

**Comment by Ufeldraku** [comment]
But it needs a premade profile for it, the ability to create it from a gui would be better.

**Comment by rilian-la-te** [comment]
You cannot create profile from UI, may create empty default profile, when no one found?

**Comment by Ufeldraku** [comment]
Yeah, that would definitely work!

**Comment by rilian-la-te** [comment]
Seems fixed (templates was installed to incorrect dir)
