### ISSUE TITLE
Can't apply custom CSS

### ISSUE THREAD

**Issue by ObadiahCrowe** [rilian-la-te/vala-panel#34]
I am attempting to apply some css to my Vala-Panel, however no matter what I do, it does not seem to effect the panel.

I'm running Arch Linux

**Comment by rilian-la-te** [comment]
Show me a CSS:)

**Comment by rilian-la-te** [comment]
CSS must be a GTK Theme CSS:)

**Comment by St1rling** [comment]
Trying to apply this: 
.-vala-panel-appmenu-private:nth-child(1) > * > GtkLabel {
  font-weight: 600;
}

**Comment by rilian-la-te** [comment]
Issue persists?

**Comment by Artillect** [comment]
I'm getting the same issue with attempting to change the font-weight property.

**Comment by rilian-la-te** [comment]
You use vala-panel?

**Comment by nick87720z** [comment]
You should use label instead of GtkLabel.
You may find more info via gtk inspector: on first (objects) tab switch to something like "show info", then change its mode to css nodes. Possible format is:
```
name {...}
.class {...} or
name.class {...}
```

**Comment by rilian-la-te** [comment]
Is this bug relevant?

**Comment by rilian-la-te** [comment]
fixed
