### ISSUE TITLE
Panel will crash if changing to Compiz

### ISSUE THREAD

**Issue by Ufeldraku** [rilian-la-te/vala-panel#36]
If I change my window manager to compiz, vala-panel will spit this out in the terminal

> (vala-panel:1416): Gtk-WARNING *_: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkToggleButton)
> *_ (vala-panel:1416): WARNING *_: Failed to fetch property `_GTK_UNIQUE_BUS_NAME': GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No existe la interfaz «org.ayatana.bamf.window» en el objeto en la ruta /org/ayatana/bamf/window/12582915
> *_ (vala-panel:1416): WARNING **: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No existe la interfaz «org.ayatana.bamf.window» en el objeto en la ruta /org/ayatana/bamf/window/12582915

**Comment by rilian-la-te** [comment]
bamfdaemon is running? It is required to run vala-panel with appmenu.

**Comment by Ufeldraku** [comment]
Yep, it's running.

**Comment by St1rling** [comment]
I have the same issue, just before vala-panel stops, bamfdaemons usage goes through the roof(30-40% cpu usage)

**Comment by rilian-la-te** [comment]
It maybe a bamfdaemon bug. appmenu does not work without BAMF.

**Comment by rilian-la-te** [comment]
Closed as invalid, because it is for https://github.com/rilian-la-te/vala-panel-appmenu
