### ISSUE TITLE
glib.h: No such file or directory 

### ISSUE THREAD

**Issue by KrystianoXPL** [rilian-la-te/vala-panel#40]
Hello. I'm trying to compile vala-panel on fedora 24, 64bit, Linux 4.5.5. I have all Dependencies installed along with glib and glib-devel. After executing cmake everything looks fine, but after trying to execute 'make' this error pops up

`[  0%] Built target i18n
[  1%] Building C object lib/CMakeFiles/valapanel.dir/misc.c.o
/home/krystianoxpl/git/vala-panel/lib/misc.c:22:18: fatal error: glib.h: No such file or directory
 #include <glib.h>`
I have already tried to put glib variable to makefile, but nothing changed

[CMakeOutput.txt](https://github.com/rilian-la-te/vala-panel/files/406644/CMakeOutput.txt)

**Comment by rilian-la-te** [comment]
Try 0.3.5 or 0.3.6 release. Master may not builds now. (For me it works, but I not guarantee building an RPM with it)

**Comment by rilian-la-te** [comment]
And look for glib.h in glib.pc and locate it. May on Fedora it needs special handling. Or just grab package from here: [http://download.opensuse.org/repositories/home:/rilian-la-te/Fedora_24/](url)

**Comment by rilian-la-te** [comment]
make package_rpm

**Comment by KrystianoXPL** [comment]
Oh right I tried to execute this and the same error popped up. So it seems I was doing right. Anyways thanks for the help!

**Comment by rilian-la-te** [comment]
Works for me
