### ISSUE TITLE
Yet Another Failed Archlinux Build

### ISSUE THREAD

**Issue by wesleyotugo** [rilian-la-te/vala-panel#41]
`
[ 35%] Linking C executable vala-panel-new
/usr/lib/gcc/i686-pc-linux-gnu/6.1.1/../../../crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[2]: *** [app/CMakeFiles/vala-panel-new.dir/build.make:123: app/vala-panel-new] Error 1
make[1]: *** [CMakeFiles/Makefile2:447: app/CMakeFiles/vala-panel-new.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
`

Here is a link to the log [at Pastebin](http://pastebin.com/UcGvnL1G)

**Comment by rilian-la-te** [comment]
Master does not builds now. Sorry. I will add main() in next commit

**Comment by rilian-la-te** [comment]
seems fixed

**Comment by wesleyotugo** [comment]
Works
