### ISSUE TITLE
apparently not starting under xfce/compiz

### ISSUE THREAD

**Issue by porkslapchop** [rilian-la-te/vala-panel#46]
I had no trouble installing vala-panel but I simply can't get it to run. I tried disabling compiz and using xfwm4 but that also didn't work. 
Using archlinux btw. Any help appreciated!

`(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_add_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_add_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_add_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_add_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_add_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_add_provider: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): Gtk-CRITICAL **: gtk_style_context_remove_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(vala-panel:28375): GLib-GObject-CRITICAL **: g_param_spec_unref: assertion 'G_IS_PARAM_SPEC (pspec)' failed
[1]    28375 segmentation fault (core dumped)  vala-panel
`

**Comment by rilian-la-te** [comment]
Try stable version or wait until it will be fixed (this evening, maybe). It will introduced With reset Master commit

**Comment by porkslapchop** [comment]
Where can I get the stable version? Build it from source myself?
btw glad to see you are updating so frequently

**Comment by porkslapchop** [comment]
nevermind its under releases

**Comment by rilian-la-te** [comment]
Fixed. Now runs, if installed from AUR.

**Comment by porkslapchop** [comment]
It's working. thank you so much!
