### ISSUE TITLE
Build failure on AUR

### ISSUE THREAD

**Issue by St1rling** [rilian-la-te/vala-panel#50]
[ 76%] Generating icontasks.c;appsystem.c;buttons.c
/home/obadiah/.cache/pacaur/vala-panel-git/src/vala-panel/applets/wnck/icontasks/buttons.vala:482.1-482.1: error: syntax error, expected identifier
]                MenuMaker.launch(app_info,null,this);
^
/home/obadiah/.cache/pacaur/vala-panel-git/src/vala-panel/applets/wnck/icontasks/buttons.vala:488.11-488.14: error: syntax error, expected `finally'
        } else {
          ^^^^
Compilation failed: 2 error(s), 0 warning(s)
make[2]: *** [applets/wnck/icontasks/CMakeFiles/icontasks.dir/build.make:73: applets/wnck/icontasks/icontasks_valac.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:1782: applets/wnck/icontasks/CMakeFiles/icontasks.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

**Comment by rilian-la-te** [comment]
fixed
