### ISSUE TITLE
Segfault on GTK 3.22

### ISSUE THREAD

**Issue by darthoctopus** [rilian-la-te/vala-panel#53]
Some apps (not all) on GTK 3.22 consistently cause vala-panel to segfault when launched:

`[48462.120318] vala-panel[9974]: segfault at 7ffd2e906ef0 ip 00007fbb7db74ed0 sp 00007ffd2e906ee0 error 6 in libglib-2.0.so.0.5000.1[7fbb7dae7000+110000]`

vala-panel also segfaults with the same messages when launched with MATE as the default panel. Sometimes it's libc instead:

`[45398.133113] vala-panel[19957]: segfault at 7ffe3b88bff8 ip 00007fd1e94bdde9 sp 00007ffe3b88bff0 error 6 in libc-2.24.so[7fd1e943a000+1bd000]`

I'm on Fedora 25 (this didn't happen on 24) so the problem might be somewhere else

**Comment by rilian-la-te** [comment]
Apps list and applet config, please

**Comment by darthoctopus** [comment]
applet config:
```[toplevel-settings]
strut=true
monitor=-1
background-type='image'
edge='top'
height=24
icon-size=16
auto-hide=false
enable-font-color=true
font-color='rgb(255,255,255)'
background-file='/usr/share/simple-panel/images/background.png'


autohide=false
use-font=true
font='Lucida Sans Unicode 14'

[0]
plugin-type='separator'
has-schema=true
can-expand=true
size=4
position=0
show-separator=false

[1]
plugin-type='menumodel'
has-schema=true
is-expanded=false
position=1
icon-name='start-here-symbolic'
menu-name=nothing
is-internal-menu=true
is-system-menu=true
is-menu-bar=false

[5]
plugin-type='separator'
has-schema=true
can-expand=true
show-separator=false
size=4
position=4

is-expanded=true

[6]
plugin-type='pager'
has-schema=false
is-expanded=false
position=5

[12]
plugin-type='xembed'
has-schema=false
is-expanded=false
position=9

[13]
plugin-type='clock'
has-schema=true
is-expanded=false
clock-format='%c'
tooltip-format='%A %x'
bold-font=false
position=10

[2]
plugin-type='appmenu-valapanel'
position=2```

not sure what you mean by apps list

**Comment by rilian-la-te** [comment]
What Apps crashes panel? And try determine crashing applet, please. To do
this: create New profile, add applets one by one, and see, when it will be
crashed

**Comment by darthoctopus** [comment]
Okay, I've verified that it's the appmenu plugin that's giving the segfaults (can also reproduce on mate-panel)

Apps that trigger (not complete list):
- Google Chrome, but only when system controls are hidden (randomly)
- Geary (when launched after panel; works fine when panel launched after it)
- California (likewise)
- Evince (likewise)
- Empty desktop (on compiz, since I'm not letting nautilus draw desktop icons; switching to an empty workspace causes segfault)

**Comment by rilian-la-te** [comment]
Fill bug against vala-panel-appmenu:) About empty workspace - I know about this, will search for workaround. Evince works for me, geary and california - try it. Chrome with hidden controls - unsupported for this setting, because native chromium buttons cannot go left (if can, will support)

**Comment by darthoctopus** [comment]
![screenshot2](https://cloud.githubusercontent.com/assets/5761408/19840182/369b2240-9ec7-11e6-9742-840adfe0f002.png)

Sure they can!

**Comment by rilian-la-te** [comment]
I also have GTK3.22:) How to move chrome buttons to the left?

**Comment by rilian-la-te** [comment]
This now only for chrome:)

**Comment by darthoctopus** [comment]
chrome respects metacity's button_layout gconf key (see the second answer to [this](http://askubuntu.com/questions/505148/can-you-fix-chromes-close-minimize-maximize-buttons-so-they-are-on-the-left))

**Comment by rilian-la-te** [comment]
Works for me
