### ISSUE TITLE
(Russian) Tracking issues in Russian.

### ISSUE THREAD

**Issue by repsac-by** [rilian-la-te/vala-panel#6]
1) В настройках перепутаны местами подписи "Цвет фона" и "Фоновое изображение".
2) "Цвет фона" не меняется как минимум под "Быстрым запуском" и "XEmbed Tray"

**Comment by rilian-la-te** [comment]
Скриншоты, будьте добры.

**Comment by repsac-by** [comment]
![settings](https://cloud.githubusercontent.com/assets/4984191/7067711/246dc170-ded6-11e4-96bb-9cd946ba1935.png)
![background](https://cloud.githubusercontent.com/assets/4984191/7067714/284c53f6-ded6-11e4-8700-3c457440f3cb.png)

**Comment by repsac-by** [comment]
Кстати, заметил только, что раделитель мне жду иконкой "рабочий стол" и треем сам съехал вниз после перезапуска, до этого был между.

**Comment by rilian-la-te** [comment]
cat конфига. А второе - это баг темы oxygen-gtk

**Comment by repsac-by** [comment]
Того конфига уже нет, я попробовал двигать, удалять, добавлять разделитель.. В итоге он сейчас вообще не отображается между иконкой стола и треем. В конфиг руками пока не лазил, все только через интерфейс с самого начала после установки из aur.

![modules](https://cloud.githubusercontent.com/assets/4984191/7071221/a156d6fc-deec-11e4-956f-c38b27c5ad89.png)

[toplevel-settings]
strut=true
monitor=-1
background-type='image'
edge='right'
height=30
icon-size=24
auto-hide=false
enable-font-color=true
font-color='rgb(255,255,255)'
background-file='/usr/share/simple-panel/images/background.png'


autohide=false
alignment='end'
panel-margin=47
use-background-file=false

width=100

dock=true
use-background-color=true
background-color='rgb(136,138,133)'

[3]
plugin-type='separator'
has-schema=true
can-expand=true
size=4
show-separator=false
position=1

is-expanded=true

[12]
plugin-type='xembed'
has-schema=false
is-expanded=false
position=4

[0]
plugin-type='wincmd'

[4]
plugin-type='wincmd'
has-schema=true
position=2

[5]
plugin-type='menumodel'

[6]
plugin-type='launchbar'

[7]
plugin-type='launchbar'
has-schema=true
position=0
launch-buttons=['geary.desktop', 'file:///home/repsac/.config/tint2/launcher/30-Debian01.desktop', 'file:///home/repsac/.config/tint2/launcher/40-Win7.desktop', 'file:///home/repsac/.config/tint2/launcher/60-cam.desktop']

[1]
plugin-type='separator'
has-schema=true
position=3
is-expanded=false

**Comment by repsac-by** [comment]
Да, действительно сменил oxygen-gtk на Default и цвет закрасился полностью.

**Comment by rilian-la-te** [comment]
Скрин того конфига, который ты опубликовал, чтоб я видел отображение его с багом.

**Comment by rilian-la-te** [comment]
Перевод поправлен в https://github.com/rilian-la-te/vala-panel/commit/e87a04e8cb493bb5baeefe799222e143cadb2e02

**Comment by rilian-la-te** [comment]
Если настройки и конфиг от одной и той же панели - то точно баг есть, потому что пустых групп без position быть не должно в конфиге.

**Comment by repsac-by** [comment]
Да, скрин настроек и конфиг делал по живому, если так можно сказать.

**Comment by rilian-la-te** [comment]
Хорошо, сейчас создам новую панель и попробую воспроизвести. Версия пакета какая?

**Comment by repsac-by** [comment]
pacaur -Qi vala-panel-git 
Название              : vala-panel-git
Версия                : 0.2.2.r0.gb377996-1
Описание              : Gtk3 panel for compositing window managers
Архитектура           : x86_64
URL                   : https://github.com/rilian-la-te/vala-panel
Лицензии              : GPL3
Группы                : Нет
Предоставляет         : vala-panel=0.2.1
Зависит от            : gtk3  libwnck3  libpeas
Дополнительно         : vala-panel-appmenu-valapanel: Global Menu
Требуется пакетами    : Нет
Дополнительно для : Нет
Конфликтует с         : Нет
Заменяет              : Нет
Установленный размер:   2,16 MiB
Сборщик               : Unknown Packager
Дата сборки           : Чт 09 апр 2015 15:31:47
Дата установки        : Чт 09 апр 2015 15:31:48
Причина установки     : Явно установлен
Установочный скрипт   : Yes
Проверен : Нет

**Comment by rilian-la-te** [comment]
Я что-то не могу воспроизвести вот такое:
```
[0]
plugin-type='wincmd'
```

без позиции и без всего такого. А с таким кривым конфигом, как получился, она либо не загрузится, либо загрузит все плагины (menumodel и вторую launchbar)

А как сама панель, юзабельно?

**Comment by rilian-la-te** [comment]
Оставляю открытым пока, когда воспроизведется баг при тестинге - пофиксим.

**Comment by repsac-by** [comment]
Попробую у себя еще раз воспроизвести баг.

В целом да, юзабельна. Мне от панели на первом этапе надо только ланчбар и древний трей.

Значит в трее мне не хватает сортировки иконок, что бы они не скакали каждый раз по разному, а были всегда примерно в одном порядке (в tint2 такое есть).

Ланчбар, можно сделать чтобы мог сканировать указанную директорию на предмет файлов .desktop. 
В ланчбар можно перетаскивать файлы это очень хорошо, но как удалить без ручного вмешательсва в конфиг я не нашёл.

**Comment by rilian-la-te** [comment]
Вытащить drag'n'drop с панели, тогда иконка удалится (так их и перемещать можно) А трей я пилить не хочу, мне лееень... (в StatusNotifier есть сортировка, а это я целиком из LXPanel взял, только баги пофиксил) Launchbar - сейчас напишу фичреквест на инглише (ибо это все же официальный язык гитхаба)

**Comment by repsac-by** [comment]
Версия                : 0.2.2.r1.ge87a04e-1
1. Удалил конфиг, запустил панель как новую.
2. Настраивал как мне надо.
3. Удалил все ненужные модули.
4. Иконка firefox из ланчбара у меня не вытаскивается, никак не получается. Думаю стоит добавить в контекстное меню пункт "удалить"
5. В следствии того, что иконка не вытаскивается решил удалить ланчбар и добавить новый.
6. Нажал на + открылся список.. Нажал 1 раз ланчбар не добавился, нажал 2 клика, добавилось 2 ланчбара.
7. Лишний решил удалить, нажал минус и получил Ошибка сегментирования.

>(vala-panel:10727): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
>Ошибка сегментирования (core dumped)

В конфиге фижу:
>[0]
plugin-type='launchbar'

>[1]
plugin-type='launchbar'
has-schema=true
position=4

**Comment by rilian-la-te** [comment]
Сейчас посмотрю, добавляется и правда долго. А по поводу удалить - это с такой системой плагинов нереально. Плагин не может отдавать разные менюшки в зависимости от места на нем. Либо можно просто запилить диалог с TreeView, где все лаунчеры перечислены, типа как в LXPanel было. Кстати, в теории на launchbar можно и обычные файлы таскать. Тогда они через xdg-open открываться будут. 

Сейчас на чистом профиле попробую воспроизвести крэш. А почему не вытаскивается? Даже если за самый край ее хватать? Что у тебя вместо десктопа?

**Comment by repsac-by** [comment]
Оно не в том дело, что долго добавляется, оно иногда с перовго клика не добавляется. Нажимаю плюсик, а Быстрый запуск уже выбран.. Кликаешь 1 раз не добавляется, кликаешь 2 раза добавляется 2 штуки. 

Вместо десктопа у меня plasma 5, если это имеется ввиду.

**Comment by rilian-la-te** [comment]
Имеется в виду, что картинку рисует и иконки? Кеды или просто KWin Standalone?

**Comment by repsac-by** [comment]
Кеды

**Comment by rilian-la-te** [comment]
В кедах я ее не тестил. Я представить не мог, что ее будут пытаться юзать там. Нафига она там, кстати?

**Comment by repsac-by** [comment]
1. Мне надо панель с ланчбаром с правой стороны монитора, там все нужные мне иконки, до которых не надо никуда лазить ни в меню ни на рабочий стол.. Они всегда есть. Их много они нужы. 
2. Мне надо старый трей. Например скайп запущеный от левого юзера рисуется только там. Keepass лучше работает там чем в кде-шной панели. И получается так, что кдешный трей монохромный, а дополнительный цветной.

**Comment by repsac-by** [comment]
В прошлой жизни в форточках я пользовался True Launch Bar. Очень настраиваеваемая, в ней так же можно было делать подменю.

**Comment by rilian-la-te** [comment]
Скайп прекрасно рисуется в SNI (я в своем плагине юзал, но и в кедах он рисуется, пробовал). Просто поставь lib32-sni-qt. А XEmbed кое-для чего нужен, да. Не спорю. 

Как кеды реагируют на вытаскивание на них иконки?
А по поводу launchbar - я баг воспроизвел, сейчас в отладчике ловить буду. Это race condition в libpeas.

**Comment by repsac-by** [comment]
lib32-sni-qt стоит. Но скайп от себя я не разу не запускал. Он у меня от разных юзеров запускается и видимо не имеет доступа к SNI.

**Comment by rilian-la-te** [comment]
К местному DBus, скорее всего. Ибо SNI (как и глобальное меню в Unity) зависят от DBus (работая в Wayland), но не зависят от X.

**Comment by repsac-by** [comment]
> Как кеды реагируют на вытаскивание на них иконки?
Смотря что куда таскать. Но вообще не очень. Стараюсь лишний раз ничего не таскать. Поведение не предсказуемое. Тащишь в одно место всплывает где-то у соседа за стенкой.

**Comment by rilian-la-te** [comment]
Если из моей панельки иконку вытащить и бросить на рандомное место в кеды?

**Comment by repsac-by** [comment]
Не получается, она не хватается даже, ничего не происходит. Нажимаю тащу 0 реакции.

**Comment by rilian-la-te** [comment]
Средней кнопкой тащи (знаю, неочевидно, но не нашел, куда забиндить)

**Comment by repsac-by** [comment]
Ха-ха.. что бы тящаить средней кнопкой мне надо загрузить форточки, там перенастроить мышь. )))  Случайно переназначил среднюю кнопку, ради эксперемента, так и осталась в мыши.

**Comment by repsac-by** [comment]
А, если тачпад?.. там же нет средней кнопки.

**Comment by rilian-la-te** [comment]
Про true launch bar не слыхал, ибо последний раз форточки серьезно юзал лет 7 назад, а по поводу подменю - в смысле подменю из launcher`ов? или просто что-то типа menumodel? Кстати, если тебе не надо делать launcher`ы в несколько строк, то лучше использовать плагин menumodel, хотя его настраивать дольше. 

Я думал над этим. Но проблема такова - левую кнопку ловит flowbox (и активирует лаунчер), а правую - панель и только она.

**Comment by repsac-by** [comment]
Имя файла меню что там должно быть?  Что за файл меню?

**Comment by rilian-la-te** [comment]
Файл меню - xml-ка, которая заменяет автоген из xdg. Пишется она в формате gmenumodel (отличие только в том, что иконки можно везде), и при выборе 'является панелью меню' верхний уровень будет целиком состоять из написанных в xml пунктов верхнего уровня (хоть подменю, хоть просто лаунчеров). Для action-name можно использовать 'launch-id', 'launch-uri' и 'launch-command'. Для action-target соответственно desktop-id, file URI или просто команду в формате Exec.

**Comment by repsac-by** [comment]
Так это то, что мне в принципе надо пойду разбираться.

**Comment by rilian-la-te** [comment]
Примерчик, однако (полностью валидный)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <menu id="places-menu">
    <section id="folders-section">
    </section>
    <section id="local-mounts">
        <item>
          <attribute name="label" translatable="yes">Computer</attribute>
          <attribute name="icon">computer</attribute>
          <attribute name="action">app.launch-uri</attribute>
          <attribute name="target">computer:///</attribute>
          <attribute name="x-dnd-source" type="b">true</attribute>
        </item>
        <item>
          <attribute name="label" translatable="yes">Trash</attribute>
          <attribute name="icon">user-trash</attribute>
          <attribute name="action">app.launch-uri</attribute>
          <attribute name="target">trash:///</attribute>
          <attribute name="x-dnd-source" type="b">true</attribute>
        </item>
    </section>
    <section id="network-mounts">
        <item>
          <attribute name="label" translatable="yes">Network</attribute>
          <attribute name="icon">network-workgroup</attribute>
          <attribute name="action">app.launch-uri</attribute>
          <attribute name="target">network:///</attribute>
          <attribute name="x-dnd-source" type="b">true</attribute>
        </item>
        <item>
          <attribute name="label" translatable="yes">Connect to server...</attribute>
          <attribute name="icon">network-server</attribute>
          <attribute name="action">app.launch-id</attribute>
          <attribute name="target">nautilus-connect-server.desktop</attribute>
          <attribute name="x-dnd-source" type="b">true</attribute>
        </item>
    </section>
    <section id="recent-section">
        <submenu id="recent-menu">
          <attribute name="label" translatable="yes">Recent documents</attribute>
          <attribute name="icon">document-open-recent</attribute>
          <attribute name="submenu-action">app.load-recent-list</attribute>
          <attribute name="hidden-when">action-disabled</attribute>
        </submenu>
    </section>
  </menu>
</interface>
```

**Comment by rilian-la-te** [comment]
Короче, крэш вроде пофиксил, а не добавляемые апплеты завтра

**Comment by rilian-la-te** [comment]
Проверь версию 0.2.3. Вроде пофиксил этот глюк с крэшами из-за неправильного создания конфига.

**Comment by repsac-by** [comment]
Перестал собираться из aur
>/tmp/pacaurtmp-repsac/vala-panel-git/PKGBUILD: line 34: cd: /tmp/pacaurtmp-repsac/vala-panel-git/src/vala-dbusmenu: Нет такого файла или каталога
==> ОШИБКА: Произошел сбой в prepare().

**Comment by rilian-la-te** [comment]
Левый пакет залил туда. Пересобери. Обновил в AUR.

**Comment by rilian-la-te** [comment]
Теперь собралось?

**Comment by repsac-by** [comment]
да

**Comment by rilian-la-te** [comment]
Будут баги - создавай новые темы или отписывайся в существующих (но в открытых). Я их буду на инглиш переименовывать.

**Comment by repsac-by** [comment]
баги есть уже креш получил просто удалял лишнее
>Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

>(vala-panel:11805): Gtk-WARNING **: gtk_window_set_titlebar() called on a realized window
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Ошибка сегментирования (core dumped)

**Comment by rilian-la-te** [comment]
Воспроизвести сможешь?

**Comment by repsac-by** [comment]
попробую.

**Comment by rilian-la-te** [comment]
Ибо крэши могут быть и от старого конфига, и кто б знал, отчего. Я вот сейчас все апплеты с дефолта (default) вычистил - ничего не вылетело.

**Comment by repsac-by** [comment]
конфигов быть не могло.. поскольку
rm -r ~/.config/vala-panel
со второй попытки пока тоже не получилось.

**Comment by rilian-la-te** [comment]
Достаточно только cp -r ~/.config/vala-panel/default ~/.config/vala-panel/old

**Comment by repsac-by** [comment]
получилось еще один раз..  
1. удалил конфиг
2. запустил панель
3. поменял цвет фона
4. нажал минус на одном из модулей

**Comment by rilian-la-te** [comment]
Пробую

**Comment by repsac-by** [comment]
3 раз получилось... Но 100% не получается в точно воспроизвести

**Comment by rilian-la-te** [comment]
Все получается, и в том же месте, и все из-за Vala. Сейчас погляжу.

**Comment by rilian-la-te** [comment]
только конфигурабельные плагины заставляют вылетать

**Comment by rilian-la-te** [comment]
Можно и cp. Панель поддерживает несколько профилей. Запускать так: vala-panel --profile <profile-name>. Имя профиля - имя папки в ~/.config/vala-panel/

**Comment by rilian-la-te** [comment]
Попробуй новую ревизию.

**Comment by repsac-by** [comment]
настройки и даже небольшой стресс тест прошла, не падает..

**Comment by rilian-la-te** [comment]
Ну и слава Богу. Extras юзал к ней (но они больше для WM, а не для кед)?

**Comment by repsac-by** [comment]
нет, не пробовал.

**Comment by rilian-la-te** [comment]
Попробуй. Кое-какие даже в кедах могут пригодиться, ИМХО (например, погодный). Но им нужен StatusNotifierWatcher (если у тебя кеды, он встроенный, если нет - можно взять из соседнего репа.) Кстати, у тебя в трее иконки не разъезжаются?

**Comment by repsac-by** [comment]
>Кстати, у тебя в трее иконки не разъезжаются?

что касается XEmbed, то вчера иконки прыгали и по положению, и по размеру. Сегодня не тестировал..

**Comment by rilian-la-te** [comment]
По положению - это нормально, как минимум пока. А вот по размеру - нет. Надо смотреть, но проблема в том, что я не пользуюсь XEmbed.

**Comment by repsac-by** [comment]
Есть еще момент в переводе не совсем корректный, при вертикальном отображении.
Высота и ширина в настройках принимают обратное значение.. Може было бы переименовать тощина и длина..  Более универсально что ли.. И там где длинна указать, что это %

**Comment by repsac-by** [comment]
Или ширина и длина лучше так наверно..

**Comment by repsac-by** [comment]
Да с gmenumodel  не разобрался, не воспринимает файл.
Пробовал менять и пересобирать встроенный так хоть какая то реакция на ошибки сыпится.
Пробовал в качестве файла подкидывать тот,  котрый встроен, тоже нет реакции.

**Comment by rilian-la-te** [comment]
Перевод можно пофиксить (если хочешь, можешь сам, это несложно).
А с gmenumodel - тот, что я подкинул, работает?

**Comment by repsac-by** [comment]
Нет, не работает, не получилось.. 
Буду пробовать фиксить сам, давно руки чесались.

**Comment by rilian-la-te** [comment]
Само меню "menu-name" - должно называться vala-panel-menu. Сейчас наварганю тебе рабочий файл, и даже проверю.

**Comment by rilian-la-te** [comment]
Точно рабочий пример, я проверил.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <menu id="vala-panel-menu">
    <section id="local-mounts">
        <item>
          <attribute name="label" translatable="yes">Computer</attribute>
          <attribute name="icon">computer</attribute>
          <attribute name="action">app.launch-uri</attribute>
          <attribute name="target">computer:///</attribute>
          <attribute name="x-dnd-source" type="b">true</attribute>
        </item>
        <item>
          <attribute name="label" translatable="yes">Trash</attribute>
          <attribute name="icon">user-trash</attribute>
          <attribute name="action">app.launch-uri</attribute>
          <attribute name="target">trash:///</attribute>
          <attribute name="x-dnd-source" type="b">true</attribute>
        </item>
    </section>
    <section id="network-mounts">
        <item>
          <attribute name="label" translatable="yes">Network</attribute>
          <attribute name="icon">network-workgroup</attribute>
          <attribute name="action">app.launch-uri</attribute>
          <attribute name="target">network:///</attribute>
          <attribute name="x-dnd-source" type="b">true</attribute>
        </item>
        <item>
          <attribute name="label" translatable="yes">Connect to server...</attribute>
          <attribute name="icon">network-server</attribute>
          <attribute name="action">app.launch-id</attribute>
          <attribute name="target">nautilus-connect-server.desktop</attribute>
          <attribute name="x-dnd-source" type="b">true</attribute>
        </item>
    </section>
    <section id="recent-section">
        <submenu id="recent-menu">
          <attribute name="label" translatable="yes">Recent documents</attribute>
          <attribute name="icon">document-open-recent</attribute>
          <attribute name="submenu-action">app.load-recent-list</attribute>
          <attribute name="hidden-when">action-disabled</attribute>
        </submenu>
    </section>
  </menu>
</interface>
```

**Comment by rilian-la-te** [comment]
Не забывай, если поправишь перевод или баг - присылать pull request.

**Comment by repsac-by** [comment]
Теперь работает, спасибо.

**Comment by rilian-la-te** [comment]
Я это закрываю, чтоб не висело. Создай новый баг, если найдешь.

**Comment by repsac-by** [comment]
ок
