### ISSUE TITLE
Config files / toplevels are not found.

### ISSUE THREAD

**Issue by jp1995** [rilian-la-te/vala-panel#65]
I've been using vala-panel for months now with no issues, super liking it. 10 minutes ago the panel randomly crashes. When I try to start it again I get:

`** (vala-panel:3194): WARNING **: Config files / toplevels are not found.`

Restarted the system, same thing. Last I updated the system was like a couple of days ago. Checked /.config/vala-panel/ and everything is still there.

What gives?

**Comment by rilian-la-te** [comment]
You are updated from 0.3 to 0.4?

**Comment by jp1995** [comment]
I didn't realize there was a 0.4

**Comment by rilian-la-te** [comment]
do you have files or folders in your `.config/vala-panel/`?
What vala-panel version are you have?

**Comment by jp1995** [comment]
Um no, vala-panel - Version 0.3.63.
In .config/vala-panel/ I have a folder called **default**, inside that is a file called _config_ and a folder called **panels**, inside that is a file called _panel_

**Comment by rilian-la-te** [comment]
You have old 0.3 config format. Now you must convert it to file-based (0.3.63 is 0.4.0 alpha 2 build 3). You must replace folder default to single file called default. For format see (default)[https://github.com/rilian-la-te/vala-panel/blob/master/data/profiles/default.in]

**Comment by rilian-la-te** [comment]
Basics:
file .config converts to global section
file panel converts to sections with UUIDs (instead of numbers).

**Comment by jp1995** [comment]
Okay, thank you!
