### ISSUE TITLE
what does this mean?

### ISSUE THREAD

**Issue by SolarAquarion** [rilian-la-te/vala-panel#67]
** (vala-panel:24307): WARNING **: Config files / toplevels are not found.

**Comment by rilian-la-te** [comment]
You have no config files or does not migrate it to new format

**Comment by SolarAquarion** [comment]
How do I migrate or create a new config

**Comment by rilian-la-te** [comment]
do you have some files in ```~/.config/vala-panel/```?

**Comment by SolarAquarion** [comment]
Yes

On Jun 29, 2017 6:56 AM, "Konstantin" <notifications@github.com> wrote:

do you have some files in ~/.config/vala-panel/?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rilian-la-te/vala-panel/issues/67#issuecomment-311932660>,
or mute the thread

**Comment by rilian-la-te** [comment]
ls, please.

**Comment by SolarAquarion** [comment]
solaraquarion@apollo   ~  ls ~/.config/vala-panel      2 ↵  1698  07:57:01 
default

**Comment by rilian-la-te** [comment]
cat default

**Comment by SolarAquarion** [comment]
i rm'ed default.

**Comment by rilian-la-te** [comment]
why? Error eliminates?

**Comment by SolarAquarion** [comment]
Yes, my default was the old one most likely.

**Comment by rilian-la-te** [comment]
Close a bug then:)
