### ISSUE TITLE
Can't start vala-panel

### ISSUE THREAD

**Issue by darthoctopus** [rilian-la-te/vala-panel#68]
I purged my old config and got this error:

```
** (vala-panel:7111): WARNING **: Cannot init global config: Can't recursively copy directory


** (vala-panel:7111): WARNING **: Config files / toplevels are not found.
```

**Comment by rilian-la-te** [comment]
Purge old config in /etc/xdg/ and reinstall vala-panel.

After done, check and close the bug.

**Comment by darthoctopus** [comment]
yep ok but more problems

**Comment by rilian-la-te** [comment]
what problems?

**Comment by darthoctopus** [comment]
nevermind, mostly went away after a second config purge

**Comment by rilian-la-te** [comment]
Maybe write series migration manual?
