### ISSUE TITLE
The "panel" doesn't stay within the window

### ISSUE THREAD

**Issue by SolarAquarion** [rilian-la-te/vala-panel#70]
If more then a certain amount of desktop apps run vala-panel doesn''t stay within one window
![screenshot_2017-08-22_16-10-49](https://user-images.githubusercontent.com/5307016/29585268-8ad07650-8754-11e7-94b3-d9d464497afe.png)

**Comment by rilian-la-te** [comment]
why are you closed it?

**Comment by SolarAquarion** [comment]
v

**Comment by rilian-la-te** [comment]
please, write description and show me screenshots.

**Comment by SolarAquarion** [comment]
Did it

**Comment by rilian-la-te** [comment]
applet list?

**Comment by SolarAquarion** [comment]
Firefox, scudcloud, messengerforFacebook, deepin-terminal, deluge,
ktorrent, and hexchat

On Aug 22, 2017 5:05 PM, "Konstantin" <notifications@github.com> wrote:

applet list?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/rilian-la-te/vala-panel/issues/70#issuecomment-324151539>,
or mute the thread

**Comment by SolarAquarion** [comment]
Discord

**Comment by rilian-la-te** [comment]
I need to know all applets on your panel, because it is applet bug AFAIK.

**Comment by rilian-la-te** [comment]
what is window list applet? XFCE's version or WnckTasklist?

**Comment by SolarAquarion** [comment]
https://ptpb.pw/RMfH

Here's the panel config

**Comment by rilian-la-te** [comment]
Did you tried XFCE tasklist?

**Comment by SolarAquarion** [comment]
I have not tried the xfce tasklist thing, is it part of the applet list?

**Comment by rilian-la-te** [comment]
yes. There is 3 tasklist implementations:)))

**Comment by SolarAquarion** [comment]
what are the 3 tasklists and I guess you need to modify the default
tasklist?

On Oct 2, 2017 7:59 AM, "Konstantin" <notifications@github.com> wrote:

yes. There is 3 tasklist implementations:)))

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/rilian-la-te/vala-panel/issues/70#issuecomment-333513740>,
or mute the thread

**Comment by rilian-la-te** [comment]
Default tasklist is WNCK thing:( Three tasklits - tasklist, tasklist-xfce and icontasks. I use icontasks:)

**Comment by SolarAquarion** [comment]
icontasks doesn't load for me

**Comment by rilian-la-te** [comment]
Why icontasks does not load? What version of panel do you have?

**Comment by SolarAquarion** [comment]
it does load, but it's too compact

**Comment by rilian-la-te** [comment]
Version of panel, please!!!!!!

tasklist-xfce?

**Comment by SolarAquarion** [comment]
both really, like only more then half of my panel is even used

**Comment by rilian-la-te** [comment]
screenshots,please. And screenshot of menu.

**Comment by SolarAquarion** [comment]
![screenshot_2017-10-02_14-56-56](https://user-images.githubusercontent.com/5307016/31080233-15dc9104-a756-11e7-8c83-119d14cacf7b.png)

**Comment by rilian-la-te** [comment]
Make xfce-tasklist expandable in config or in GUI, like this.
![screenshot at 2017-10-02 16-45-46](https://user-images.githubusercontent.com/1329638/31080321-06c7d3e6-a791-11e7-81e9-e3e5bbc9cd83.png)

**Comment by rilian-la-te** [comment]
Can I close this?

**Comment by SolarAquarion** [comment]
Yes

On Nov 17, 2017 4:27 PM, "Konstantin" <notifications@github.com> wrote:

Can I close this?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/rilian-la-te/vala-panel/issues/70#issuecomment-345369803>,
or mute the thread
