### ISSUE TITLE
Menus Don't Open Under The AppMenu

### ISSUE THREAD

**Issue by furqaanshamsi** [rilian-la-te/vala-panel#71]
Some reason, under XFCE in Mint 18.2, the panels don't open under the corresponding title. Doesn't matter which one, it's always shown under the window itself. 
![screenshot_2017-09-23_16-43-34](https://user-images.githubusercontent.com/27899310/30777407-6a536dc6-a07f-11e7-93cb-26d45df23ff5.png)

**Comment by rilian-la-te** [comment]
What module are you use? unity-gtk-module or appmenu-gtk-module?

**Comment by Artillect** [comment]
@furqaanshamsi How did you manage to change the font weight to bold for the application name? For some reason the font-weight property isn't changing on my end, but all of the other properties I've changed work just fine.

**Comment by rilian-la-te** [comment]
There is a compile-time switch for it:-)))

**Comment by rilian-la-te** [comment]
Closing this, if relevant, suggest moving to https://github.com/rilian-la-te/vala-panel-appmenu
