### ISSUE TITLE
Close button for prefereces dialog

### ISSUE THREAD

**Issue by JaneShilikova** [rilian-la-te/vala-panel#75]
![2017-12-17 20-46-41](https://user-images.githubusercontent.com/27082432/34082256-d88235c8-e36b-11e7-87e3-a4adb5328ade.png)

**Comment by rilian-la-te** [comment]
But I have it)))
![correct](https://user-images.githubusercontent.com/1329638/34084647-21c3db64-e395-11e7-9855-24f0263c1c5a.png)
