### ISSUE TITLE
Please update submodules

### ISSUE THREAD

**Issue by nick87720z** [rilian-la-te/vala-panel#76]
I'm gentoo user, and prefered way to install everything there is via ebuilds. As for cmake packages, they even don't provide uninstall targets, like e.g. autotools do. For now submodule update is broken by missing commit in lib/dbusmenu. I can handle it via terminal in cloned sources, but git eclasses don't provide (yet) way to run `$ git submodule update --remote`.

As i found, it should be pretty simple to do yet another extra run of:
`git submodule update --remote && git commit -a` .

**Comment by rilian-la-te** [comment]
For dbusmenu this is simple, because it is not generated.
For cmake-vala it will not work, because half of files in it is autogenerated.

**Comment by rilian-la-te** [comment]
dbusmenu is updated
