### ISSUE TITLE
Xembed segfault, when geany editor starts

### ISSUE THREAD

**Issue by nick87720z** [rilian-la-te/vala-panel#80]
I have geany-1.32 with plugins, for code editing. Though i did not enable systray icon - after start, as i noticed with xfce panel, its tray changes size many times during fraction of second, though icon doesn't appear finally. However, for vala-panel it causes segmentation fault.

Can't give useful dump right now, because all gtk stuff is again built optimized after big rebuild (to remove abi_x86_32 from all possible apps). If it can be useful:
https://gist.github.com/nick87720z/b3122c58f5abcfd8b6910b3b7f09fd88

Will do better dump after rebuilding these libs back to debuggable.

**Comment by nick87720z** [comment]
https://gist.github.com/nick87720z/758994825925ea8086447c86be0527e0

**Comment by rilian-la-te** [comment]
Test with LXDE tray, please.

**Comment by nick87720z** [comment]
From this http://github.com/rilian-la-te/vala-panel-extras ?

**Comment by rilian-la-te** [comment]
No, from https://git.lxde.org/gitweb/?p=lxde/lxpanel.git;a=summary

**Comment by nick87720z** [comment]
Tried with lxpanel-0.9.3. Tray icon appears from shortest moment, then disappears. No crash.

**Comment by rilian-la-te** [comment]
Will look for it.

**Comment by rilian-la-te** [comment]
Works for me with ArchLinux:
![screenshot at 2018-01-07 03-48-06](https://user-images.githubusercontent.com/1329638/34645403-b84743dc-f35d-11e7-94e7-980b0de8f693.png)

Please, write your CFLAGS and libraries (GLib and GTK3)
Try to upgrade your GLib to 2.52, please.

**Comment by nick87720z** [comment]
Yep, problem disappeared after glib update (with some other updates) and panel rebuild.
