### ISSUE TITLE
Please drop ru.mo file

### ISSUE THREAD

**Issue by sunweaver** [rilian-la-te/vala-panel#81]
Hi,

in the sources of the 0.3.71 release, I found a binary file, namely ru.mo. Please remove that from the source tree. Thanks!

Mike

**Comment by rilian-la-te** [comment]
Ok, will look for it, will check source tree and tarball generator script.

**Comment by rilian-la-te** [comment]
In master I do not have such file, so, I will check tarball generator.

**Comment by sunweaver** [comment]
The 0.3.71 tarball has po/ru.mo...

**Comment by rilian-la-te** [comment]
Sorry, will make 0.3.72 tarball this evening. For 0.3.71 you can do this:
Close repo at tag 0.3.71
Update submodules to latest
make dist.

And use this as reference tarball.

**Comment by rilian-la-te** [comment]
Do it exists for 0.3.73

**Comment by sunweaver** [comment]
On  Mo 22 Jan 2018 21:05:13 CET, Konstantin wrote:

> Do it exists for 0.3.73

Looks good now.
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
