### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by kirigayakazushin** [rilian-la-te/vala-panel#83]
I ran make install, it was installed on the system, but there was no uninstall in the makefile.

**Comment by rilian-la-te** [comment]
1. Why you do not like it?
2. For uninstall CMake project use ```xargs rm < install_manifest.txt```

**Comment by kirigayakazushin** [comment]
@rilian-la-te  Thank you, I like it, just noticed that there is no uninstall.
