### ISSUE TITLE
Vala panel doesn't update self-position when updating screen resolution

### ISSUE THREAD

**Issue by ghostplant** [rilian-la-te/vala-panel#85]
For a vala-panel displayed at bottom edge, when changing the screen resolution, the panel position is not updated, which results in panel missing in screen or sitting in the middle of screen.

**Comment by rilian-la-te** [comment]
Only at bottom? Or on top and left/right also?

**Comment by ghostplant** [comment]
For top, the horizontal position can be automatic scaled correctly, and its vertical position is always 0 no matter what resolution to change.
For bottom, the horizontal position can be automatic scaled correctly as well, but its vertical position keeps still, so we either see the panel laid in the middle of screen or missing outside screen.
For left/right, I never tried that due to useless.

**Comment by ghostplant** [comment]
So actually, if the panel is laid on the top edge, this bug can be ignored. But there is another bug that is annoying.

I use vala-panel as the default gtk panel and caja as the default desktop filemanager. Caja manages the desktop icons and background. However, even if I set "Reverse Space" to be enabled for vala-panel, there is still a SMALL possibility after every login that "Reverse Space" is disabled, which makes part of top desktop icons are hidden by the panel.

So in a word, if I put the vala-panel on top edge, there is "Reverse Space" covering desktop icons problem, and if I put it on the bottom edge, there is panel missing problem on resolution updates.

**Comment by rilian-la-te** [comment]
I do not see this. How are you start a vala-panel?

**Comment by ghostplant** [comment]
The main issue can be easily reproduced in virtualbox with ubuntu 18.04 and vala-panel installed. Put the vala-panel on south and use `xrandr` or any other tools for resolution updates.

**Comment by rilian-la-te** [comment]
Cannot confirm on master on current ArchLinux
I need more info:
1. Used applets, and is it reproducible with empty panel.
2. Version of all dependencies (GLib, GTK, Libpeas, especially GTK)
3. Version of panel.
4. Window manager (Marco, I guess).

**Comment by ghostplant** [comment]
This snapshot is the bug example of "Reserve Space" not working, which doesn't always happen.
![a](https://user-images.githubusercontent.com/12099308/35807591-252cc414-0abe-11e8-9b79-47466fa09184.png)

**Comment by ghostplant** [comment]
As for "No position update on changing resolution", I just found that this issue doesn't happen in virtualbox and qemu-kvm (all kernels, driver version, system library version, vala-panel version, and vala applets configuration are kept same as physical host).

So I think this might be not related to softwares such as desktop environment, but video driver might be the root-cause. Vala-panel encounters this issue on NV-card using default nouveau driver, and I cannot try other drivers at the moment due to lacking infrastructures.

"Reserve Space" will happen on both physical host and virtual machines.

**Comment by ghostplant** [comment]
Besides, I installed lxpanel (gtk2-based) and it doesn't have this issue when updating resolution.

**Comment by rilian-la-te** [comment]
This is an old methods actually, thanks for pointing me. I will revert it once I reach home.

There is another geometry bug,

**Comment by rilian-la-te** [comment]
And this bug will be remain a tracker for both.

**Comment by ghostplant** [comment]
OK, hope this bug can be fixed before ubuntu1804 is released ~

**Comment by rilian-la-te** [comment]
Check, and if fixed, write here)

**Comment by rilian-la-te** [comment]
Or close this and create new bug about strut)

**Comment by rilian-la-te** [comment]
Tried to modify resolution - it works) So, it will be fixed, if you confirm)

**Comment by ghostplant** [comment]
Thanks, it is fixed now, and now this issue can be close :)
