### ISSUE TITLE
Lock MenuItem required on vala-panel MenuModel

### ISSUE THREAD

**Issue by ghostplant** [rilian-la-te/vala-panel#90]
Different desktop have different lock-screen/screensaver commands, this configurable MenuItem is needed.

**Comment by rilian-la-te** [comment]
But on many desktops lock screen is in logout window and commands can overlap.

**Comment by rilian-la-te** [comment]
But if you want it and do it in your branch, can you implement a lock action property, not as you do?

**Comment by ghostplant** [comment]
Desktops like gnome and mate have different commands to trigger screensaver (lock) and session-switch (another kind of lock).

I think I can add some lines to extend 1 more action, but I am actually annoying at the build system because it doesn't work well will debian packaging framework.

**Comment by rilian-la-te** [comment]
Why? Explain, please.
