### ISSUE TITLE
Cancel or Allow disabling mid-click for wincmd

### ISSUE THREAD

**Issue by ghostplant** [rilian-la-te/vala-panel#93]
Mid-click on wincmd will trigger size shrink on all window, and it is very easy to be triggered by accidental use and it makes current session not as expected.
Is it possible to set a line on configuration file to disable this mid-client event?

**Comment by ghostplant** [comment]
My branch is just to force remove this event:

https://github.com/ghostplant/vala-panel/commit/a0476068840415dc27fa42885da4c48eae3f6eef#diff-9d57a55037c9340745b4582e2479040d

**Comment by rilian-la-te** [comment]
Removing is no way. Option - maybe.

**Comment by ghostplant** [comment]
Yes, it is OK to work in the same way as `use-toolbar-appearance=true`.

**Comment by ghostplant** [comment]
This option is of high priority to me. If you are busy, I'll help to to support it according to the implementation of https://github.com/rilian-la-te/vala-panel/commit/26c7e44fbf87b71970d13160a437760daee6f3ef. Is it OK for you or for me to make it?

**Comment by rilian-la-te** [comment]
this feature is possible, wait a bit

**Comment by rilian-la-te** [comment]
But there is an option already:
```xml
    <key name="middle-button-command" enum="org.valapanel.WcCommand">
      <default>'shade'</default>
    </key>
``` 
You just need to set it to none.

**Comment by ghostplant** [comment]
Fixed with https://github.com/rilian-la-te/vala-panel/pull/95/files
