### ISSUE TITLE
[CRASH BUG] Vala-panel on Linux without gvfs-backends

### ISSUE THREAD

**Issue by ghostplant** [rilian-la-te/vala-panel#94]
If the system have no gvfs-backends installed, clicking `Place -> Network` and `Place -> Connect to server...` will crash the vala-panel and no longer any panel restart.

**Comment by ghostplant** [comment]
If `nautilus-connect-server.desktop` doesn't exist, or `network:///` is not accessible, the panel will crash instantly.

**Comment by rilian-la-te** [comment]
On click? Or instantly?

**Comment by rilian-la-te** [comment]
If on click, this is known issue and can be fixed to ignore, if you provide a backtrace.

**Comment by ghostplant** [comment]
after click

**Comment by rilian-la-te** [comment]
But who wants to use GVFS entries without GVFS installed?

**Comment by ghostplant** [comment]
gvfs is fat

**Comment by rilian-la-te** [comment]
And, users then should use GVFS URIs without it?

**Comment by rilian-la-te** [comment]
Provide a backtraces for one ID case and one URI case, please.

**Comment by ghostplant** [comment]
It is easy to reproduce the crash of ID case: just move and backup the desktop file with
`sudo mv /usr/share/applications/nautilus-connect-server.desktop /`
then `Place -> Connect to server...` will crash.

**Comment by ghostplant** [comment]
Fixed with: https://github.com/rilian-la-te/vala-panel/pull/95/files

**Comment by rilian-la-te** [comment]
PR merged.

**Comment by ghostplant** [comment]
Updated Vala-panel has been placed as the default panel in my Ubuntu 18.04 : )

Snaps: https://github.com/ghostplant/ubuntu-classic/blob/master/img-flashback-bionic.png

**Comment by rilian-la-te** [comment]
Thanks)
