### ISSUE TITLE
Chromium wrong application name

### ISSUE THREAD

**Issue by Taur10** [rilian-la-te/vala-panel#98]
Self explanatory, no? For some reason this only happens in Chromium (Chrome/Chromium loves being a special snowflake), but instead of reading Chromium the application name is Discord. Everything works fine, it's just a bit weird to see the wrong name up there.

Speaking of things, any chance of finding a way to give menus to applications like Telegram that don't really have them? Maybe some way a user could build one?

**Comment by rilian-la-te** [comment]
1. This is an appmenu bug, open it there, please. And then show me a screen, please.

And repeat questions there too.

I will close this, because you wrote to a wrong project.

Actual project about menus: https://github.com/rilian-la-te/vala-panel-appmenu
